# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies
  pod "youtube-ios-player-helper"

  target 'MoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesUITests' do
    # Pods for testing
  end

end
